### ISSUE TITLE
Some basic question regarding yarn: passing arguments

### ISSUE THREAD

**Issue by q2000foo** [RienNeVaPlus/wikifolio-example#1]
Hello,

it's me again with another basic question : )

Currently, running

`yarn start`

runs a process of _index.ts_, which is prompting for email and password input from the console. 

Would it be possible to pass these parameters (and possibly others, like wikifolio ID) via flags to the call, rather than being prompted to enter them? Something along the lines of

`yarn start --email thisIsMy@emailAddress.de --password verySecretPassword`

would be convenient to have (with an optional keyboard prompt if no flags are passed). 
However, since I don't know enough of yarn and typescript I'm not certain if and how this would be feasible.

Cheers

**Comment by RienNeVaPlus** [comment]
I've implemented only a very basic arguments feature, because I don't want to pollute the repository with 3rd-party libs which would've been required otherwise and might pose a security threat. We're already on very sensitive grounds with these plaintext credentials.

```bash
yarn start test@example.org myPa$$w0rd
```
